application: marketplacr 
version: 1
runtime: python27
api_version: 1
threadsafe: false

libraries:
- name: jinja2
  version: latest

handlers:
- url: /.*
  script: main.py

builtins:
- remote_api: on
